// Maintainer preparation, not the migration executor. Regeneration invalidates receipts.
import { readFile, writeFile, mkdir, readdir, cp, mkdtemp, rm } from "node:fs/promises";
import path from "node:path";
import { tmpdir } from "node:os";
import { createHash } from "node:crypto";
import { pathToFileURL } from "node:url";
import { hydrate, material, source, project, pins, executor } from "./hydrate.mjs";
const {analyze} = await import(pathToFileURL(path.join(executor, "dist/analyze.js")));
const {createPlan} = await import(pathToFileURL(path.join(executor, "dist/plan.js")));
const {eventStreamOracle} = await import(pathToFileURL(path.join(executor, "dist/event-stream.js")));
const hash = b => createHash("sha256").update(b).digest("hex");
const put = async (name,data) => {const p=path.join(material,name);await mkdir(path.dirname(p),{recursive:true});await writeFile(p,data);};
const json = (name,value) => put(name,JSON.stringify(value,null,2)+"\n");
await hydrate();
const analysis = await analyze(source);
analysis.source = path.relative(project,source).split(path.sep).join("/");
const refs = ["dependency-reference/API.go.txt",...pins.referenceFiles.map(f=>"dependency-reference/"+f)];
for (const name of refs) {const b=await readFile(path.join(source,name));analysis.files.push({path:name,sha256:hash(b),lines:b.toString().split("\n").length,test:false,exports:[],imports:[]});}
analysis.files.sort((a,b)=>a.path.localeCompare(b.path));
await json("analysis.json",analysis);
const stages = [
 {id:"foundation", sources:["files","process","diagnostics","model"], outputs:["files.go","process.go","process_unix.go","process_windows.go","diagnostics.go","model.go","foundation_test.go"], behavior:"File integrity, exclusive task locks, child-process cancellation and model/environment configuration.", detail:`Implement files.ts, process.ts, diagnostics.ts and model.ts completely. Preserve strict relative paths, reject symbolic links, SHA-256 and atomic writes; never overwrite dependencies/judges through candidate tooling. Locks are exclusive and released on failure. Process execution uses cleanEnv's allowlist, captures diagnostics, cancels child process groups where supported and reports timeout/truncation/cancellation separately. Default timeout and output limit are unlimited (zero); explicitly supplied budgets are honored. Use platform files for process group handling and a Windows fallback with documented limitations. ConfiguredModel reads PORTSMITH_* then OMNI_*, validates HTTP(S) URLs without credentials, uses Pith's known DeepSeek catalog capacities (Flash 1,000,000 context / 384,000 output), supports PORTSMITH_CONTEXT_WINDOW/MAX_TOKENS, and does not serialize the key. Unknown compatible model fallback and validation match source. LoadLocalEnv preserves existing process values and Node dotenv quote/comment semantics. Hash/fingerprint encodings and deterministically sorted records must retain source semantics.`},
 {id:"analysis", sources:["analyze","plan"], outputs:["analyze.go","plan.go","typescript.go","analysis_test.go"], behavior:"TypeScript AST/module-resolution analysis and reviewable v1 draft plans.", detail:`Use embedded TypeScript 5.9.3 through pinned Goja, not regular expressions as an AST replacement. Supply an explicit read-only TypeScript resolution/config host (ts.sys is a getter in the compiler bundle; assigning it does not work), with filesystem callbacks and tsconfig parsing/module-resolution support; transpile the small bridge to ES5 if necessary. Support imports, reexports, import type, require, dynamic/computed imports, .js-to-.ts NodeNext resolution, aliases, workspace package classification, declaration files, SCC cycles, exports, lines and hashes exactly as analyze.ts. Preserve wildcard fallback and node_modules alias distinctions. Hidden/build/dependency trees and symlinks are skipped. Analyze returns the original version-1 JSON schema with source canonicalized. CreatePlan writes the original draft plan shape, rules, README, dependencies, package-cycle warnings and exact analysis hash. This is deterministic analysis, never a model call. Cancel CPU-bound Goja work with runtime.Interrupt and release resources. Do not cache reports across changed files.`},
 {id:"workspace", sources:["workspace"], outputs:["workspace.go","workspace_test.go"], behavior:"Immutable task snapshots, writable candidates and fingerprints.", detail:`Port all prepareTask/loadTask/writeCandidate/editCandidate/candidateFiles/fingerprint semantics. PrepareOptions maps the TS options: File.Name/Data are in-memory seed/initial/judge files; empty optional strings are absent. Initial files must be module-owned writable outputs. Seed files and judge files are distinct and immutable. Required judge names, race and moduleTask survive task.json. Copy the source LICENSE; freeze source/config/manifest/judge/seed bytes with the source JSON field names. Refuse local Go module replaces, paths outside the root and symbolic links. Prepare creates a new task directory and must not overwrite an existing one. CandidateFiles includes go.mod/go.sum/LICENSE and permitted files in deterministic order. Verification/acceptance flags are not inferred from compilation.`},
 {id:"verification", sources:["verify","event-stream","oracle-worker"], outputs:["verify.go","event_stream.go","verification_test.go"], behavior:"Isolated Go verification, live TS oracle and distinct native receipts.", detail:`Preserve all verifier phases: gofmt writable files, isolated copy, compile, vet, meaningful non-skipped candidate tests, frozen independent tests, required judge name completeness and optional race instrumentation. Candidates may not write reserved judge test names or paths. VerifyPort returns the original report schema; version=1, verifier=portsmith-native-go-v1, fullParityProven=false. CurrentVerification rejects stale fingerprints or old TS verifier identity. The EventStream example must execute the supplied original TS file in embedded Goja, transpiled using the fixed compiler, run all seven original scenarios, retain cancellation tests and run judgeCheck's known-broken negative control; a stored constant golden is not the oracle. No Node, tsx or subprocess JS runtime. Promise microtasks can drain when Goja returns to Go. Provide Symbol.asyncIterator when absent using a well-known symbol shim before executing the transpiled module. Isolate source oracle execution from Go filesystem/process access and honor cancellation. Unexpected unresolved asynchronous results are errors. Output semantics need not keep the TS worker process; this is an intentional Go adaptation.`},
 {id:"backend", sources:["agent"], outputs:["agent.go","agent_test.go"], behavior:"Pith coding-agent tool/repair loop, persistent sessions and model resilience.", detail:`Use github.com/minifish-org/pith/packages/coding-agent.CreateAgentSession directly with native read/write/edit/bash/grep/find/ls plus custom verify_candidate. The custom tool invokes VerifyPort and reports actionable phase diagnostics, but never commits/accepts. Use explicit Cwd, resources, settings, per-session model credentials and a durable OpenSession manager under the task's pith-sessions directory. Resume the current Pith conversation and import supported legacy message logs only with validated roles; do not pretend Pi session JSONL is Pith JSONL. Expose the actual SessionFile and Resumed flag in RunReport. Bind context/timeout to Prompt/Abort and always unsubscribe/Close the session and caller-owned manager. Use Pith's catalog model compat (including DeepSeek thinking), full declared context/output capacities, retry, partial-tool rejection and length continuation. Supply a real summarizer through RunPolicy.Summarize so auto-compaction is enabled, using the configured provider and Pith's compaction prompt/helpers; preserve failed-summary rollback and never execute partial length tool calls. Zero MaxTurns/Timeout means unlimited. Explicit limits produce an interrupted/limited report and preserve files. Log tool progress, nonsecret model identity, turns, token usage and unknown-cost status. The optional StreamFn field is for offline testing and is passed into Pith; nil uses the native provider. Respect normal Pith skill/context/template resources; document that Pi JS extensions require Go hooks and are not directly executable. Write source-equivalent migration instructions into the system prompt and feedback, preserving all readonly boundaries. Do not substitute a hand-written model loop for the SDK.`},
 {id:"workflow", sources:["state","migrate","modules"], outputs:["state.go","migrate.go","modules.go","workflow_test.go"], behavior:"v1/v2 execution, cumulative independent gates, repair, recovery, additive baselines and commits.", detail:`Port complete state.ts/migrate.ts/modules.ts behavior, including preflight for every step before the first model call, all-prepared and available-steps policies, same-module writable accumulation, prior-module readonly seeds, immutable static assets, dependency DAGs, ownership checks, source and plan hashes, baseline Git ancestry/blob checks, separate additive journals and a repository-wide lock. Required tests are cumulative; no stage may erase previous acceptance. Generate receives context/task root/diagnostic feedback and returns RunReport; nil is invalid for an executing run, but --check never needs it. Zero MaxAttempts/MaxUnits means unlimited/all; positive values apply per invocation exactly as upstream. Each accepted step saves a checkpoint; only a verified complete module is integrated and committed. Refuse unrelated working-tree/staged changes and never push. Preserve transactional pending states, reverify after staging/project integration, recover interrupted commits and avoid duplicate generation/commits on rerun. Source output schemas and status labels stay compatible, but native journals have an executor identity or distinct verifier seal to reject TS in-flight journals. Port planStatus/next/taskStatus/acceptTask, stale verification and changed exports. Acceptance includes the receipt and refuses an existing export directory. Candidate self-tests must include pending-transaction recovery, multi-module cumulative failure, assets, all-prepared gaps, baseline tampering and ownership collisions from the original tests; the independent suite is a minimum, not the complete required behavior.`},
 {id:"delivery", sources:["cli","demo"], outputs:["cli.go","demo.go","cli_test.go"], behavior:"Complete CLI, standalone binary, source mappings and delivery documentation.", detail:`Main(ctx,args,stdout,stderr) int implements every source CLI command/flag and exit behavior: analyze, plan, prepare (including --plan/--unit and --example event-stream), run, judge-check, verify, status, next, accept, migrate, help. Repeatable --file and strict numeric validation remain. Wire migrate.Generate to RunPort with lazy model initialization so --check is offline and needs no key. cmd/portsmith/main.go connects signal cancellation and exit status. The source demo.ts is an optional demo command/helper or an equivalent documented Go example; map this development workflow explicitly. Build one binary for macOS arm64, Linux amd64 and Windows amd64 with CGO disabled. Runtime analyze/help must work with no Node/Go/Git on PATH; Go verification still requires a Go toolchain and migration integration requires Git. Bundle the TypeScript license/notices and list all dependencies honestly. Provide docs/USAGE.md, docs/COMPATIBILITY.md and docs/THIRD_PARTY.md in English. docs/source-map.json is an array: {source,sha256,exports,goFiles,status,notes}; every original runtime TS file exactly once, actual Go files, status ported/adapted, explicit notes for adaptations. No empty placeholders or claims of exhaustive equivalence.`},
];
const runtimeFiles = analysis.files.filter(f=>/^src\/[^/]+\.ts$/.test(f.path));
const tests = analysis.files.filter(f=>f.path.startsWith("test/") && f.test).map(f=>f.path);
const shared = [...tests,...refs];
const output = f => "internal/portsmith/"+f;
const modules=[{id:"portsmith",dependsOn:[],batches:stages.map(s=>s.id)}];
const batches=[], execution={}, mapping=[];
const api=await readFile(path.join(material,"API.go.txt"),"utf8");
for(const [i,s] of stages.entries()){
 const sources=s.sources.map(f=>"src/"+f+".ts");
 const references=[...new Set([...runtimeFiles.map(f=>f.path).filter(f=>!sources.includes(f)),...shared])];
 const outputs=s.outputs.map(output);
 if(s.id==="delivery")outputs.push("cmd/portsmith/main.go","docs/USAGE.md","docs/COMPATIBILITY.md","docs/THIRD_PARTY.md","docs/source-map.json");
 const assets=s.id==="analysis"?await Promise.all(["typescript.txt","typescript-LICENSE.txt","typescript-NOTICE.txt","goja-LICENSE.txt","pith-LICENSE.txt"].map(async name=>({source:"assets/"+name,target:output(name),sha256:hash(await readFile(path.join(material,"assets",name)))}))):[];
 const judgePath="judges/"+s.id+"/internal/portsmith";
 const judgeText=(await Promise.all((await readdir(path.join(material,judgePath))).filter(n=>n.endsWith("_test.go")).map(n=>readFile(path.join(material,judgePath,n),"utf8")))).join("\n");
 const required=[...judgeText.matchAll(/^func\s+(TestPortsmithJudge\w+)\s*\(/gm)].map(m=>m[1]);
 batches.push({id:s.id,module:"portsmith",dependsOn:i?[stages[i-1].id]:[],sources,references,outputs:[...outputs,...assets.map(a=>a.target)],behaviors:[s.behavior],acceptance:required});
 execution[s.id]={status:"ready",steps:[{id:"port",sources:[...sources,...references],goal:s.behavior+" Implement the complete source-owned behavior; run candidate tests and the frozen cumulative judge before finishing.",contract:"contracts/"+s.id+".md",judge:"judges/"+s.id,outputs,tests:required,race:s.id==="foundation"||s.id==="backend",...(assets.length?{assets}:{})}]};
 await put("contracts/"+s.id+".md",`# ${s.id}\n\n${s.detail}\n\nRead all source-owned files and the supplied upstream tests. Earlier outputs in the same module remain writable; preserve their acceptance. Implement additional internal helpers freely within the manifest.\n\n## Shared Go boundary\n\nThe following is a compile-only API contract for all stages. Implement only the functions owned by this stage and dependencies required by it; later-stage functions are not required early. JSON-returning functions preserve the matching TypeScript schema. Types may be placed in the owning source file. This empty implementation is a negative control and MUST NOT be copied into product code.\n\n\`\`\`go\n${api}\n\`\`\`\n`);
 for(const name of sources){const file=runtimeFiles.find(f=>f.path===name);if(!file)throw Error("unmapped source "+name);mapping.push({source:name,sha256:file.sha256,exports:file.exports,batch:s.id,goFiles:outputs.filter(f=>f.endsWith(".go")&&!f.endsWith("_test.go")),strategy:["agent","oracle-worker","demo"].includes(path.basename(name,".ts"))?"adapt":"port"});}
}
if(mapping.length!==runtimeFiles.length||new Set(mapping.map(f=>f.source)).size!==runtimeFiles.length)throw Error("Runtime source ownership is incomplete");
await json("plan.json",{version:2,source:analysis.source,revision:pins.portsmith.revision,analysisSha256:hash(await readFile(path.join(material,"analysis.json"))),modules,batches});
await json("workflow.json",{version:2,project:"..",runs:".portsmith/runs",startPolicy:"all-prepared",bootstrap:["migration","go.mod","go.sum",".gitignore","README.md"],batches:execution});
await json("source-map.json",mapping);
await json("scope.json",{source:pins.portsmith,backend:pins.pith,runtimeFiles:runtimeFiles.length,runtimeLines:runtimeFiles.reduce((n,f)=>n+f.lines,0),testFiles:tests.length,testLines:analysis.files.filter(f=>tests.includes(f.path)).reduce((n,f)=>n+f.lines,0),modules:1,batches:stages.length,steps:stages.length,modelBackendForMigration:"Pi coding-agent / DeepSeek Flash",productBackend:"Pith coding-agent",language:"Go",cgo:false,retainedThirdPartyJavaScript:"TypeScript 5.9.3 compiler executed inside Goja",excluded:["Portsmith's npm development toolchain is replaced by Go tooling","Pi JavaScript extension host is replaced by Pith Go hooks; no automatic plugin translation","In-flight Pi sessions and TS executor journals are not binary-compatible; use a fresh native run"]});
await json("judges/delivery/internal/portsmith/testdata/source-hashes.json",Object.fromEntries(runtimeFiles.map(f=>[f.path,f.sha256])));

const fixture=path.join(material,"judges/analysis/internal/portsmith/testdata/analysis");
const golden=await analyze(path.join(fixture,"input"));golden.source="<fixture>";await writeFile(path.join(fixture,"expected.json"),JSON.stringify(golden,null,2)+"\n");
const temp=await mkdtemp(path.join(tmpdir(),"portsmith-plan-golden-"));
try{
 const p=await createPlan(path.join(fixture,"expected.json"),path.join(temp,"plan"),"reviewed-revision");await writeFile(path.join(fixture,"plan.json"),JSON.stringify(p,null,2)+"\n");
 const oracleDir=path.join(material,"judges/verification/internal/portsmith/testdata/oracle");
 await mkdir(path.join(temp,"references/packages/ai/src/utils"),{recursive:true});await cp(path.join(oracleDir,"event-stream.txt"),path.join(temp,"references/packages/ai/src/utils/event-stream.ts"));
 const oracle=await eventStreamOracle(temp);await writeFile(path.join(oracleDir,"expected.json"),JSON.stringify(oracle,null,2)+"\n");
}finally{await rm(temp,{recursive:true,force:true});}
console.log(`Reviewed material generated: ${runtimeFiles.length} source files, ${stages.length} steps. No model calls.`);
